insert into post (author, content) values ('anonymous', 'What do you call a belt made out of watches? A waist of time.')
insert into post (author, content) values ('anonymous', 'What does the roof say to the house? I got you covered.')
insert into post (author, content) values ('anonymous', 'What did one ocean say to another ocean? Nothing they just waved.')
insert into post (author, content) values ('anonymous', 'Never trust an atom...They make up everything!')
insert into post (author, content) values ('anonymous', 'I''m reading a book about anti-gravity. I can''t put it down.')
insert into post (author, content) values ('anonymous', 'To the guy who invented zero: Thanks for nothing!')
insert into post (author, content) values ('anonymous', 'I was up all night wondering where the sun went, but then it dawned on me.')
insert into post (author, content) values ('anonymous', 'I was wondering why the baseball was getting bigger. Then it hit me.')
insert into post (author, content) values ('anonymous', 'A backwards poet writes inverse.')
insert into post (author, content) values ('anonymous', 'Orion''s Belt is a huge waist of space.')
insert into post (author, content) values ('anonymous', 'What did the grape say when it was stepped on? Nothing, it just let out a little wine.')
insert into post (author, content) values ('anonymous', 'Why can''t a bicycle stand on its own? Because it''s two tired.')
insert into post (author, content) values ('anonymous', 'What do you get from a pampered cow? Spoiled milk.')
insert into post (author, content) values ('anonymous', 'What did the monkey say when he caught his tail in the revolving door? It won''t be long now!')
insert into post (author, content) values ('anonymous', 'Why shouldn''t you write with a broken pencil? BECAUSE IT''S POINTLESS!')
insert into post (author, content) values ('anonymous', 'A neutron walks into a bar and asks, "how much for a beer?" The bartender says, "for you? no charge."')
insert into post (author, content) values ('anonymous', 'How does an octopus go to war? WELL-ARMED!')
insert into post (author, content) values ('anonymous', 'What kind of horses go out after dusk? Nightmares!')
insert into post (author, content) values ('anonymous', 'A magician was driving down the road...then he turned into a drive way.')
insert into post (author, content) values ('anonymous', 'What washes up on tiny beaches? MICROWAVES!')
insert into post (author, content) values ('anonymous', 'Why do crabs never give to charity? Because they''re shellfish.')
insert into post (author, content) values ('anonymous', 'Last night I dreamed that I was a muffler. I woke up exhausted.')
insert into post (author, content) values ('anonymous', 'Why did the skeleton hit the party solo? He had no body to go with him.')
insert into post (author, content) values ('anonymous', 'Why don''t skeletons watch scary movies? They just don''t have the guts.')
insert into post (author, content) values ('anonymous', 'A man walks into a zoo, the only animal was a dog. It was a shitzu.')